#!/bin/bash
# gds - Git Deploy Setup

if [ -z $1 ]; then
	echo "Configure server to receive deploy:"
	echo "./script server [path]"
	echo ""
	echo "Configure local repo do deploy:"
	echo "./script local [remote path] [ssh user] [ssh host] [ssh port]"
	exit
fi

# server setup
if [ $1 == "server" ]; then
	path=$(pwd);
	echo "Setting up server to deploy a git app"
	# no path
	if [ -z $2 ]; then
		path="${path}/project"
	else
		# absolute path
		if [ $(echo $2 | grep '^/') ]; then
			path="${2}"
			# relative path
		else
			path="${path}/${2}"
		fi
	fi
	# remove last slash from path
	if [ $(echo $path | grep '/$') ]; then
		path=$(echo $path | sed 's/\/$//')
	fi

	path_git="${path}/app.git"
	mkdir -pv $path_git
	git init --bare $path_git
	echo -e "#!/bin/bash
git --work-tree=$path --git-dir=$path_git checkout -f" >> "${path_git}/hooks/post-receive"
	chmod +x "${path_git}/hooks/post-receive"
	echo ""
	echo "Finished"

	# local setup
elif [ $1 == "local" ]; then
	path=$2
	user=$3
	host=$4
	port=$5
	# remove last slash from path
	if [ $(echo $path | grep '/$') ]; then
		path=$(echo $path | sed 's/\/$//')
	fi
	if [ -z $2 ] || [ -z $3 ] || [ -z $4 ]; then
		echo "Correct way:"
		echo ""
		echo "./script local [remote path] [ssh user] [ssh host] [ssh port]"
	else
		if [ -d ".git/" ]; then
			echo "Setting up local repo to deploy a git app"
			# verify if port is a number
			if [ $5 -eq $5 2>/dev/null ]; then
				git remote add deploy ssh://$user@$host:$port$path/app.git
			else
				git remote add deploy $user@$host:$path/app.git
			fi
			git config --global alias.pud "push -f deploy HEAD:master"
			echo ""
			echo "To deploy your current repo type:"
			echo ""
			echo "git pud"
		else
			echo "Not a git repository"
		fi
	fi
fi

