#!/bin/bash

case $BLOCK_BUTTON in
	1) terminator -e nmtui ;;
	3) notify-send "🌐 Internet module" "\- Click to connect
📡: no wifi connection
📶: wifi connection with quality
❎: no ethernet
🌐: ethernet working
" ;;
esac

[ "$(cat /sys/class/net/w*/operstate)" = 'down' ] && wifiicon="📡"

[ ! -n "${wifiicon+var}" ] && wifiicon=$(grep "^\s*w" /proc/net/wireless | awk '{ print "📶", int($3 * 100 / 70) "%" }')

[ ! -z "$wifiicon" ] && printf  "%s " "$wifiicon"

printf "%s" "$(cat /sys/class/net/e*/operstate | sed "s/down/❎/;s/up/🌐/")"
